import "./globals.css";
import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";

const courier = Courier_Prime({
  weight: ["400", "700"],
  subsets: ["latin"],
  fallback: ["system-ui", "arial"],
  variable: "--customCourier",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${courier.variable}`}>
        {/* <NavigationBar /> */}
        {children}
      </body>
    </html>
  );
}
