import "./globals.css";
import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";
import { Inter } from "next/font/google";

// Globals font
const main = Inter({
  weight: ["300", "400", "600", "700"],
  subsets: ["latin"],
  fallback: ["system-ui", "arial"],
  variable: "--customMain",
});

const courier = Courier_Prime({
  weight: ["400", "700"],
  subsets: ["latin"],
  fallback: ["system-ui", "arial"],
  variable: "--customCourier",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${courier.variable} ${main.variable}`}>
      <body className="font-main bg-slate-50">
        {/* <NavigationBar /> */}
        {children}
      </body>
    </html>
  );
}
